services:
  arcane:
    image: ghcr.io/getarcaneapp/arcane:latest
    container_name: arcane
    restart: unless-stopped
    ports:
      - 3552:3552
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
      - ./backups:/backups # Cambia esta ruta por la ubicación de tus backups de volúmenes
      - /host/path/to/projects:/host/path/to/projects # Cambia esta ruta por la ubicación de tus proyectos
    environment:
      - APP_URL=${APP_URL}
      - PROJECTS_DIRECTORY=/host/path/to/projects # Asegúrate de que esta ruta coincida con la ruta del volumen 
      - PUID=1000
      - PGID=1000
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - JWT_SECRET=${JWT_SECRET}

volumes:
  arcane_data:
    name: arcane_data

# añadir estas líneas para proxy inverso 
networks:
  default:
    external: true
    name: proxy